---
- name: Destroy Proxmox storage
  hosts: proxmox
  gather_facts: true
  tasks:
    - name: "01 Load storage configuration"
      ansible.builtin.set_fact:
        proxstorage: "{{ lookup('template', 'templates/proxstorage/' + inventory_hostname + '.yml.j2') | from_yaml }}"

    - name: "02 Remove Proxmox storage configuration"
      ansible.builtin.blockinfile:
        path: /etc/pve/storage.cfg
        marker: "# {mark} ANSIBLE MANAGED proxstorage"
        block: |
          lvmthin: {{ proxstorage.storage_name }}
              thinpool {{ proxstorage.thinpool_name }}
              vgname {{ proxstorage.vg_name }}
              content rootdir,images
        state: absent
      notify:
        - Restart pvedaemon
        - Restart pveproxy
        - Restart pvestatd

    - name: "03 Remove thin volumes"
      ansible.builtin.lvol:
        vg: "{{ proxstorage.vg_name }}"
        lv: "{{ item }}"
        state: absent
        force: true
      loop: "{{ proxstorage.thin_volumes }}"

    - name: "04 Remove thin pool"
      ansible.builtin.lvol:
        vg: "{{ proxstorage.vg_name }}"
        thinpool: "{{ proxstorage.thinpool_name }}"
        state: absent
        force: true

    - name: "05 Remove volume group"
      ansible.builtin.lvg:
        vg: "{{ proxstorage.vg_name }}"
        state: absent
        force: true

    - name: "06 List logical volumes"
      ansible.builtin.command: lvs --units g
      register: lvs_output
      changed_when: false

    - name: "07 Show logical volumes"
      ansible.builtin.debug:
        var: lvs_output.stdout_lines

    - name: "08 List storages"
      ansible.builtin.command: pvesm status
      register: storage_status
      changed_when: false

    - name: "09 Show storages"
      ansible.builtin.debug:
        var: storage_status.stdout_lines

  handlers:
    - name: Restart pvedaemon
      ansible.builtin.service:
        name: pvedaemon
        state: restarted

    - name: Restart pveproxy
      ansible.builtin.service:
        name: pveproxy
        state: restarted

    - name: Restart pvestatd
      ansible.builtin.service:
        name: pvestatd
        state: restarted
