---
# dto_proxreport.yml — v0.2.1
# - Fix: no loop on block; loop only on tasks
# - Adds SMBIOS collection per VM via qm config / qm showcmd

- name: Show Proxmox host status
  hosts: proxmox
  gather_facts: true
  tasks:
    - name: "01 List storages"
      ansible.builtin.command: pvesm status
      register: storage_status
      changed_when: false

    - name: "02 Show storages"
      ansible.builtin.debug:
        var: storage_status.stdout_lines

    - name: "03 List Proxmox network configuration"
      ansible.builtin.command: >
        pvesh get /nodes/{{ ansible_hostname }}/network --output-format json
      register: network_config
      changed_when: false

    - name: "04 Show network configuration"
      ansible.builtin.debug:
        msg: "{{ network_config.stdout | from_json | to_nice_yaml }}"

    - name: "05 Show IP addresses"
      ansible.builtin.command: ip -o addr show
      register: ip_addr_output
      changed_when: false

    - name: "06 Display IP addresses"
      ansible.builtin.debug:
        var: ip_addr_output.stdout_lines

    - name: "07 Show Proxmox version"
      ansible.builtin.command: pveversion
      register: pve_version
      changed_when: false

    - name: "08 Display Proxmox version"
      ansible.builtin.debug:
        var: pve_version.stdout_lines

    - name: "09 List block devices"
      ansible.builtin.command: lsblk --output NAME,SIZE,TYPE,MOUNTPOINT
      register: block_devices
      changed_when: false

    - name: "10 Show block devices"
      ansible.builtin.debug:
        var: block_devices.stdout_lines

    - name: "11 Gather CPU details"
      ansible.builtin.command: lscpu
      register: cpu_details
      changed_when: false

    - name: "12 Display CPU details"
      ansible.builtin.debug:
        var: cpu_details.stdout_lines

    - name: "13 Gather memory details"
      ansible.builtin.command: free -h
      register: memory_details
      changed_when: false

    - name: "14 Display memory details"
      ansible.builtin.debug:
        var: memory_details.stdout_lines

    - name: "15 Get system uptime"
      ansible.builtin.command: uptime -p
      register: uptime
      changed_when: false

    - name: "16 Show system uptime"
      ansible.builtin.debug:
        var: uptime.stdout

    - name: "17 List virtual machines"
      ansible.builtin.command: qm list
      register: vm_list
      changed_when: false

    - name: "18 Extract VMIDs"
      ansible.builtin.command: bash -lc "qm list | awk 'NR>1 {print $1}'"
      register: vmids_raw
      changed_when: false

    - name: "19 Set VMID list"
      ansible.builtin.set_fact:
        vmids: "{{ vmids_raw.stdout_lines | select('match','^\\d+$') | list }}"

    # -------- Für jede VM SMBIOS sammeln (ohne loop auf block!) --------
    - name: "20 Collect SMBIOS with qm config"
      ansible.builtin.command: "qm config {{ item }}"
      register: qm_cfg_per_vm
      loop: "{{ vmids }}"
      loop_control:
        label: "vmid={{ item }}"
      changed_when: false

    - name: "21 Collect QEMU showcmd (pretty)"
      ansible.builtin.command: "qm showcmd {{ item }} --pretty"
      register: qm_showcmd_per_vm
      loop: "{{ vmids }}"
      loop_control:
        label: "vmid={{ item }}"
      changed_when: false

    - name: "22 Build per‑VM SMBIOS summary"
      ansible.builtin.set_fact:
        smbios_summary: >-
          {{
            dict(
              vmids | zip(
                qm_cfg_per_vm.results
                | map(attribute='stdout_lines')
                | map('select','match','^smbios1:')
                | map('list')
              )
            )
          }}

    - name: "23 Show SMBIOS summary (smbios1 lines)"
      ansible.builtin.debug:
        var: smbios_summary

    - name: "24 Collect data for report"
      ansible.builtin.set_fact:
        proxreport_data:
          storage_status: "{{ storage_status.stdout_lines }}"
          network_config: "{{ network_config.stdout | from_json }}"
          ip_addresses: "{{ ip_addr_output.stdout_lines }}"
          pve_version: "{{ pve_version.stdout_lines }}"
          block_devices: "{{ block_devices.stdout_lines }}"
          cpu_details: "{{ cpu_details.stdout_lines }}"
          memory_details: "{{ memory_details.stdout_lines }}"
          uptime: "{{ uptime.stdout }}"
          creation_date: "{{ ansible_date_time.iso8601 }}"
          vm_list: "{{ vm_list.stdout_lines }}"
          vmids: "{{ vmids }}"
          smbios_summary: "{{ smbios_summary | default({}) }}"
        cacheable: true

    - name: "25 Build Proxmox summary HTML"
      ansible.builtin.template:
        src: templates/proxmox_summary.html.j2
        dest: proxmox-summary.html
      delegate_to: localhost
      run_once: true
