---
- name: Destroy Proxmox storage
  hosts: proxmox
  gather_facts: true
  tasks:
    - name: "01 Load storage configuration"
      ansible.builtin.set_fact:
        proxstorage: "{{ lookup('template', 'templates/proxstorage/' + inventory_hostname + '.yml.j2') | from_yaml }}"

    - name: "02 Remove Proxmox storage configuration"
      ansible.builtin.command: "pvesm remove {{ proxstorage.storage_name }}"
      register: remove_storage
      failed_when: false
      changed_when: remove_storage.rc == 0
      notify:
        - Restart pvedaemon
        - Restart pveproxy
        - Restart pvestatd

    - name: "03 Remove thin pool"
      ansible.builtin.lvol:
        vg: "{{ proxstorage.vg_name }}"
        thinpool: "{{ proxstorage.thinpool_name }}"
        state: absent
        force: true

    - name: "04 Remove volume group"
      ansible.builtin.lvg:
        vg: "{{ proxstorage.vg_name }}"
        state: absent
        force: true

    - name: "05 List logical volumes"
      ansible.builtin.command: lvs --units g
      register: lvs_output
      changed_when: false

    - name: "06 Show logical volumes"
      ansible.builtin.debug:
        var: lvs_output.stdout_lines

    - name: "07 List storages"
      ansible.builtin.command: pvesm status
      register: storage_status
      changed_when: false

    - name: "08 Show storages"
      ansible.builtin.debug:
        var: storage_status.stdout_lines

  handlers:
    - name: Restart pvedaemon
      ansible.builtin.service:
        name: pvedaemon
        state: restarted

    - name: Restart pveproxy
      ansible.builtin.service:
        name: pveproxy
        state: restarted

    - name: Restart pvestatd
      ansible.builtin.service:
        name: pvestatd
        state: restarted
