---
- name: Show Proxmox host status
  hosts: proxmox
  gather_facts: true
  tasks:
    - name: "01 List storages"
      ansible.builtin.command: pvesm status
      register: storage_status
      changed_when: false

    - name: "02 Show storages"
      ansible.builtin.debug:
        var: storage_status.stdout_lines

    - name: "03 List Proxmox network configuration"
      ansible.builtin.command: >
        pvesh get /nodes/{{ ansible_hostname }}/network --output-format json
      register: network_config
      changed_when: false

    - name: "04 Show network configuration"
      ansible.builtin.debug:
        msg: "{{ network_config.stdout | from_json | to_nice_yaml }}"

    - name: "05 Show IP addresses"
      ansible.builtin.command: ip -o addr show
      register: ip_addr_output
      changed_when: false

    - name: "06 Display IP addresses"
      ansible.builtin.debug:
        var: ip_addr_output.stdout_lines

    - name: "07 Show Proxmox version"
      ansible.builtin.command: pveversion
      register: pve_version
      changed_when: false

    - name: "08 Display Proxmox version"
      ansible.builtin.debug:
        var: pve_version.stdout_lines

    - name: "09 List block devices"
      ansible.builtin.command: lsblk --output NAME,SIZE,TYPE,MOUNTPOINT
      register: block_devices
      changed_when: false

    - name: "10 Show block devices"
      ansible.builtin.debug:
        var: block_devices.stdout_lines

    - name: "11 Ensure lshw is installed"
      ansible.builtin.package:
        name: lshw
        state: present
      become: true

    - name: "12 Gather hardware details"
      ansible.builtin.command: lshw -json
      register: hardware_details
      changed_when: false
      become: true

    - name: "13 Show hardware details"
      ansible.builtin.debug:
        var: hardware_details.stdout

    - name: "14 Get system uptime"
      ansible.builtin.command: uptime -p
      register: uptime
      changed_when: false

    - name: "15 Show system uptime"
      ansible.builtin.debug:
        var: uptime.stdout

    - name: "16 List virtual machines"
      ansible.builtin.command: qm list
      register: vm_list
      changed_when: false

    - name: "17 Show virtual machines"
      ansible.builtin.debug:
        var: vm_list.stdout_lines

    - name: "18 Collect data for summary"
      ansible.builtin.set_fact:
        proxstat_data:
          storage_status: "{{ storage_status.stdout_lines }}"
          network_config: "{{ network_config.stdout | from_json }}"
          ip_addresses: "{{ ip_addr_output.stdout_lines }}"
          pve_version: "{{ pve_version.stdout_lines }}"
          block_devices: "{{ block_devices.stdout_lines }}"
          hardware_details: "{{ hardware_details.stdout }}"
          uptime: "{{ uptime.stdout }}"
          creation_date: "{{ ansible_date_time.iso8601 }}"
          vm_list: "{{ vm_list.stdout_lines }}"

    - name: Build Proxmox summary HTML
      ansible.builtin.template:
        src: templates/proxmox_summary.html.j2
        dest: proxmox-summary.html
      delegate_to: localhost
      run_once: true
